class SpeedtestService {
  const SpeedtestService({
    required this.name,
    required this.url,
    required this.regions,
    required this.measures,
    required this.operator,
    required this.note,
  });

  final String name;
  final String url;
  final List<String> regions;
  final String measures;
  final String operator;
  final String note;
  bool get isCis => regions.contains('Россия и СНГ');
}

// Ookla and Yandex are pinned. Each remaining group follows the Tranco K9Z7W
// domain rank checked on 2026-10-08; brand reach is only a popularity proxy.
const speedtestServices = <SpeedtestService>[
  SpeedtestService(
    name: "Speedtest by Ookla",
    url: "https://www.speedtest.net/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "Ookla",
    note: "Выбор ближайшего сервера или страны вручную",
  ),
  SpeedtestService(
    name: "Яндекс Интернетометр",
    url: "https://yandex.ru/internet",
    regions: ["Россия и СНГ"],
    measures: "Скачивание и отдача",
    operator: "Яндекс",
    note: "Показывает сведения о подключении",
  ),
  SpeedtestService(
    name: "FAST.com",
    url: "https://fast.com/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка под нагрузкой",
    operator: "Netflix",
    note: "Запускает измерение при открытии",
  ),
  SpeedtestService(
    name: "M-Lab",
    url: "https://speed.measurementlab.net/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка",
    operator: "Measurement Lab",
    note: "NDT; результаты публикуются как открытые данные",
  ),
  SpeedtestService(
    name: "SpeedOf.Me",
    url: "https://speedof.me/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка",
    operator: "SpeedOf.Me",
    note: "Последовательные измерения в браузере",
  ),
  SpeedtestService(
    name: "SpeedSmart",
    url: "https://speedsmart.net/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping",
    operator: "Veeapps",
    note: "HTML5-тест с выбором сервера",
  ),
  SpeedtestService(
    name: "nPerf",
    url: "https://www.nperf.com/en/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка",
    operator: "нPerf SAS",
    note: "Можно выбрать сервер измерения",
  ),
  SpeedtestService(
    name: "OpenSpeedTest",
    url: "https://openspeedtest.com/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "OpenSpeedTest",
    note: "HTML5-тест без установки приложения",
  ),
  SpeedtestService(
    name: "Speedcheck",
    url: "https://www.speedcheck.org/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping",
    operator: "Etrality GmbH",
    note: "Браузерная проверка соединения",
  ),
  SpeedtestService(
    name: "Bandwidth Place",
    url: "https://www.bandwidthplace.com/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка",
    operator: "Bandwidth Place",
    note: "Тест соединения в браузере",
  ),
  SpeedtestService(
    name: "LibreSpeed",
    url: "https://librespeed.org/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "LibreSpeed",
    note: "Открытый исходный код; выбор сервера",
  ),
  SpeedtestService(
    name: "Fusion Connect",
    url: "https://www.fusionconnect.com/speed-test-plus",
    regions: ["Мир"],
    measures: "Скачивание, отдача, задержка, jitter",
    operator: "Fusion Connect",
    note: "Проверка пригодности соединения для связи",
  ),
  SpeedtestService(
    name: "Meter.net",
    url: "https://www.meter.net/",
    regions: ["Мир"],
    measures: "Скачивание, отдача, ping",
    operator: "Meter.net",
    note: "Выбор измерительного сервера",
  ),
  SpeedtestService(
    name: "Selectel",
    url: "https://speedtest.selectel.ru/",
    regions: ["Россия и СНГ"],
    measures: "Скачивание, отдача, ping",
    operator: "Selectel",
    note: "Связь с дата-центром",
  ),
  SpeedtestService(
    name: "Ростелеком",
    url: "https://www.rt.ru/checkup",
    regions: ["Россия и СНГ"],
    measures: "Скачивание и отдача",
    operator: "Ростелеком",
    note: "Проверка домашнего подключения",
  ),
  SpeedtestService(
    name: "Билайн",
    url: "https://moskva.beeline.ru/customers/products/home/speedtest/",
    regions: ["Россия и СНГ"],
    measures: "Скачивание и отдача",
    operator: "ВымпелКом",
    note: "Проверка домашнего интернета",
  ),
  SpeedtestService(
    name: "Уфанет",
    url: "https://speedtest.ufanet.ru/",
    regions: ["Россия и СНГ"],
    measures: "Скачивание, отдача, ping",
    operator: "Уфанет",
    note: "Тест в сети оператора",
  ),
  SpeedtestService(
    name: "Speedtest.ru",
    url: "https://speedtest.ru/",
    regions: ["Россия и СНГ"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "Speedtest.ru",
    note: "Продвинутый режим и выбор сервера",
  ),
  SpeedtestService(
    name: "UZTELECOM",
    url: "https://speedtest.uz/",
    regions: ["Россия и СНГ", "Узбекистан"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "Узбектелеком",
    note: "Тест в сети Узбекистана",
  ),
  SpeedtestService(
    name: "AT&T",
    url: "https://www.att.com/support/speedtest/",
    regions: ["Америка", "США"],
    measures: "Скачивание и отдача",
    operator: "AT&T",
    note: "Проверка домашнего подключения",
  ),
  SpeedtestService(
    name: "Vodafone Speedtest Plus",
    url: "https://speedtest.vodafone.de/",
    regions: ["Европа", "Германия"],
    measures: "Скачивание, отдача, ping",
    operator: "Vodafone",
    note: "Тест для клиентов разных провайдеров",
  ),
  SpeedtestService(
    name: "Bell",
    url: "https://support.bell.ca/Internet/Internet-Speed-Test",
    regions: ["Америка", "Канада"],
    measures: "Скачивание и отдача",
    operator: "Bell",
    note: "Проверка домашнего подключения",
  ),
  SpeedtestService(
    name: "SIMET",
    url: "https://simet.nic.br/",
    regions: ["Америка", "Бразилия"],
    measures: "Скачивание, отдача, задержка, потери",
    operator: "NIC.br",
    note: "Бразильский тест качества интернета",
  ),
  SpeedtestService(
    name: "UFC-Que Choisir",
    url: "https://www.quechoisir.org/outil-speedtest-n64483/",
    regions: ["Европа", "Франция"],
    measures: "Скачивание, отдача, задержка",
    operator: "Que Choisir Ensemble",
    note: "Тест ассоциации потребителей",
  ),
  SpeedtestService(
    name: "MyBroadband",
    url: "https://speedtest.mybroadband.co.za/",
    regions: ["Африка", "ЮАР"],
    measures: "Скачивание, отдача, ping",
    operator: "MyBroadband",
    note: "Измерительные серверы Южной Африки",
  ),
  SpeedtestService(
    name: "Speedtest.cn",
    url: "https://www.speedtest.cn/",
    regions: ["Азия", "Китай"],
    measures: "Скачивание, отдача, ping",
    operator: "SpeedTest.cn",
    note: "Серверы в Китае",
  ),
  SpeedtestService(
    name: "SpeedTest.pl",
    url: "https://www.speedtest.pl/",
    regions: ["Европа", "Польша"],
    measures: "Скачивание, отдача, ping",
    operator: "V-SPEED",
    note: "Польский тест и рейтинги провайдеров",
  ),
  SpeedtestService(
    name: "Minha Conexão",
    url: "https://www.minhaconexao.com.br/",
    regions: ["Америка", "Бразилия"],
    measures: "Скачивание, отдача, ping",
    operator: "Minha Conexão",
    note: "Бразильский тест и рейтинг провайдеров",
  ),
  SpeedtestService(
    name: "Google Fiber",
    url: "https://fiber.google.com/speedtest/",
    regions: ["Америка", "США"],
    measures: "Скачивание, отдача, ping",
    operator: "Google Fiber",
    note: "Тест доступен клиентам любых провайдеров",
  ),
  SpeedtestService(
    name: "Breitbandmessung",
    url: "https://breitbandmessung.de/",
    regions: ["Европа", "Германия"],
    measures: "Скачивание и отдача",
    operator: "Bundesnetzagentur",
    note: "Тест немецкого регулятора",
  ),
  SpeedtestService(
    name: "Ariase",
    url: "https://www.ariase.com/box/test-vitesse",
    regions: ["Европа", "Франция"],
    measures: "Скачивание, отдача, ping",
    operator: "Ariase",
    note: "Французский тест на базе nPerf",
  ),
  SpeedtestService(
    name: "RTR Netztest",
    url: "https://www.netztest.at/en/",
    regions: ["Европа", "Австрия"],
    measures: "Скачивание, отдача, задержка",
    operator: "RTR",
    note: "Тест австрийского регулятора",
  ),
  SpeedtestService(
    name: "Broadband Speed Checker",
    url: "https://www.broadbandspeedchecker.co.uk/",
    regions: ["Европа", "Великобритания"],
    measures: "Скачивание, отдача, задержка",
    operator: "Speedchecker",
    note: "Сравнение широкополосных подключений",
  ),
  SpeedtestService(
    name: "DegroupTest",
    url: "https://www.degrouptest.com/test-debit.php",
    regions: ["Европа", "Франция"],
    measures: "Скачивание, отдача, ping",
    operator: "DegroupTest",
    note: "Измерение на базе nPerf",
  ),
  SpeedtestService(
    name: "Bredbandskollen",
    url: "https://www.bredbandskollen.se/",
    regions: ["Европа", "Швеция"],
    measures: "Скачивание, отдача, задержка",
    operator: "Internetstiftelsen",
    note: "Независимый шведский тест",
  ),
  SpeedtestService(
    name: "Speedtest.sg",
    url: "https://www.speedtest.sg/",
    regions: ["Азия", "Сингапур"],
    measures: "Скачивание, отдача, ping",
    operator: "NewMedia Express",
    note: "Связь с дата-центром Сингапура",
  ),
  SpeedtestService(
    name: "DSL.cz",
    url: "https://www.dsl.cz/test-mereni-rychlosti",
    regions: ["Европа", "Чехия"],
    measures: "Скачивание, отдача, ping",
    operator: "DSL.cz",
    note: "Проверка домашнего подключения",
  ),
  SpeedtestService(
    name: "CNMC",
    url: "https://calidadtelecos.cnmc.gob.es/test-velocidad",
    regions: ["Европа", "Испания"],
    measures: "Скачивание, отдача, задержка",
    operator: "CNMC",
    note: "Тест испанского регулятора",
  ),
  SpeedtestService(
    name: "AKOS Test Net",
    url: "https://www.akostest.net/",
    regions: ["Европа", "Словения"],
    measures: "Скачивание, отдача, задержка",
    operator: "AKOS",
    note: "Тест словенского регулятора",
  ),
  SpeedtestService(
    name: "Netograf",
    url: "https://www.netograf.ro/",
    regions: ["Европа", "Румыния"],
    measures: "Скачивание, отдача, задержка",
    operator: "ANCOM",
    note: "Тест румынского регулятора",
  ),
  SpeedtestService(
    name: "NetMeter",
    url: "https://www.netmeter.eu/",
    regions: ["Европа", "Чехия"],
    measures: "Скачивание, отдача, ping",
    operator: "INTERNET.cz",
    note: "Европейские измерительные серверы",
  ),
  SpeedtestService(
    name: "Speedtest.ch",
    url: "https://www.speedtest.ch/",
    regions: ["Европа", "Швейцария"],
    measures: "Скачивание, отдача, ping, jitter",
    operator: "speedtest.ch",
    note: "Измерение на базе OpenSpeedTest",
  ),
  SpeedtestService(
    name: "Bittimittari",
    url: "https://www.bittimittari.fi/fi",
    regions: ["Европа", "Финляндия"],
    measures: "Скачивание, отдача, задержка, качество",
    operator: "Traficom",
    note: "Тест финского регулятора",
  ),
];
