package control

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/levvs-one/sora-client/core/errs"
)

// TokenLen is the length of a control-plane authenticator. The contract carries
// it in a bytes field on Connect and Disconnect, so it is compared rather than
// parsed: a wrong length is a wrong token, not a different format.
const TokenLen = 32

// tokenFile is the name of the authenticator file inside the data directory of
// the core. The file is the only place where the token lives at rest, and it is
// readable by the account that owns the core data directory: the interface needs
// it to authenticate, and nothing else does.
const tokenFile = "control.token"

// Authenticator checks the token a client presents on Connect and Disconnect.
//
// The control-plane transport is already restricted to the local machine and to
// the account that may talk to the core, so this token does not defend the
// machine from a remote attacker. It defends it from the two neighbours that do
// exist: another process of the same account that found the socket, and a stale
// client from a previous run of the interface. Comparison is constant time, and
// the token is generated by the operating system.
type Authenticator struct {
	mu    sync.RWMutex
	token []byte
}

// NewAuthenticator returns an authenticator for an existing token. The token is
// copied, so the caller may wipe its own.
func NewAuthenticator(token []byte) (*Authenticator, error) {
	if len(token) != TokenLen {
		return nil, errs.Newf(errs.CodeInvalidArgument, errs.KeyUnauthenticated,
			"control: the authenticator must be %d bytes, got %d", TokenLen, len(token))
	}
	return &Authenticator{token: append([]byte(nil), token...)}, nil
}

// LoadOrCreateToken returns the authenticator of the data directory, generating
// and storing one the first time the core starts. An existing file that is not a
// token is refused rather than replaced: overwriting it would silently
// disconnect a running interface, and a corrupt file must be visible.
func LoadOrCreateToken(dir string) (*Authenticator, error) {
	if strings.TrimSpace(dir) == "" {
		return nil, errs.Newf(errs.CodeInvalidArgument, errs.KeyUnauthenticated,
			"control: no data directory for the authenticator")
	}
	path := filepath.Join(dir, tokenFile)
	raw, err := os.ReadFile(path) //nolint:gosec // a fixed file name inside the data directory of the core
	switch {
	case err == nil:
		token, decodeErr := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw)))
		if decodeErr != nil || len(token) != TokenLen {
			return nil, errs.Newf(errs.CodeInternal, errs.KeyUnauthenticated,
				"control: the stored authenticator is not readable")
		}
		return NewAuthenticator(token)
	case !errors.Is(err, fs.ErrNotExist):
		return nil, errs.Wrap(err, errs.CodeInternal, errs.KeyUnauthenticated)
	}
	token := make([]byte, TokenLen)
	if _, err := rand.Read(token); err != nil {
		return nil, errs.Wrap(err, errs.CodeInternal, errs.KeyUnauthenticated)
	}
	encoded := []byte(base64.StdEncoding.EncodeToString(token))
	if err := writeOwnerOnly(path, encoded); err != nil {
		return nil, err
	}
	return NewAuthenticator(token)
}

// Verify reports whether a presented token is the one this core issued. A
// missing, short or long token is refused without comparison, and the comparison
// itself runs in constant time.
func (a *Authenticator) Verify(presented []byte) bool {
	if a == nil || len(presented) != TokenLen {
		return false
	}
	a.mu.RLock()
	expected := a.token
	a.mu.RUnlock()
	if len(expected) != TokenLen {
		return false
	}
	return subtle.ConstantTimeCompare(presented, expected) == 1
}

// Check returns the catalog error for a failed verification, so a caller does
// not have to build it and cannot forget the key.
func (a *Authenticator) Check(presented []byte) error {
	if a.Verify(presented) {
		return nil
	}
	return errs.Newf(errs.CodeUnauthenticated, errs.KeyUnauthenticated,
		"control: the presented authenticator does not match")
}

// Token returns a copy of the current token, which Handshake gives to a client
// the transport admitted.
func (a *Authenticator) Token() []byte {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return append([]byte(nil), a.token...)
}

// Rotate replaces the token and returns the new one. A core that suspects its
// token has been read rotates without a restart; every existing client is then
// refused, which is the intended effect.
func (a *Authenticator) Rotate() ([]byte, error) {
	fresh := make([]byte, TokenLen)
	if _, err := rand.Read(fresh); err != nil {
		return nil, errs.Wrap(err, errs.CodeInternal, errs.KeyUnauthenticated)
	}
	a.mu.Lock()
	a.token = append([]byte(nil), fresh...)
	a.mu.Unlock()
	return fresh, nil
}

// writeOwnerOnly stores a file that only the owner may read.
func writeOwnerOnly(path string, data []byte) error {
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return errs.Wrap(err, errs.CodeInternal, errs.KeyUnauthenticated)
	}
	return nil
}
