name: sora
description: "Sora"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.13.5

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_links: ^7.2.2
  cupertino_icons: ^2.0.0
  dbus: ^0.7.15
  ffi: ^2.2.0
  file_selector: ^1.1.0
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  flutter_localizations:
    sdk: flutter
  grpc: ^5.1.0
  http2: ^2.3.1
  intl: any
  nativeapi: ^0.3.0
  protobuf: ^6.1.0
  retry: ^3.1.2
  shared_preferences: ^2.5.6
  tray_manager: ^0.7.0
  url_launcher: ^6.3.3
  win32: ^6.4.0
  window_manager: ^0.5.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: false
  generate: true
  assets:
    - assets/tray/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
