<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SoraUpgrade</AssemblyName>
    <RootNamespace>v2rayUpgrade</RootNamespace>
    <Product>Sora Updater</Product>
    <AssemblyTitle>Sora Updater</AssemblyTitle>
    <Company>Sora Contributors</Company>
    <Copyright>Copyright © 2019-2020 v2rayN contributors; 2026 Sora contributors (GPLv3)</Copyright>
    <Version>0.2.0</Version>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
